/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ee459cbefd562d5c896385dfdbf8fddc)
interface __BaseEnv_Env {
	LIVE_STATE: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
